# Generated by Django 5.1.4 on 2025-01-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_cart_ordered_remove_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
