# Generated by Django 5.1.4 on 2025-01-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_shopper_username_alter_shopper_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shopper',
            managers=[
            ],
        ),
    ]
